layout_spectrum: 0.5553191
color:
  saturation: 0
  brandStrength: 0
  lightness: 0
  rhythmicContrast: 0
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
typography_spectrum: 0.5510638
name: Become the Future
